# Autogenerated wrapper script for sshpass_jll for armv7l-linux-musleabihf
export sshpass

JLLWrappers.@generate_wrapper_header("sshpass")
JLLWrappers.@declare_executable_product(sshpass)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        sshpass,
        "bin/sshpass",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
